### ISSUE TITLE
Define the categories

### ISSUE THREAD

**Issue by r-marques** [nevermined-io/cryptoarts#7]
### What

Update the categories for the artwork use case

### How

As a first cut I propose to just add the categories from the [figma designs](https://www.figma.com/file/qbvI8d1LQ353WlzUf0Y5Hp/Nevermined?node-id=1154%3A0) and we can add more later

**Comment by Cintiaaguiarp** [comment]
- Digital Photography 
- Photo-painting
- Digital Collage
- 3D Renders
- 3D Models
- VR Experiences
- Generative Art
- Mixed Media
- Sound Design
- Wearables
- Fine Art
- Digital Painting

**Comment by Cintiaaguiarp** [comment]
Folder for images 
https://drive.google.com/drive/u/8/folders/1XQtq2_PDIbDGxpmakpDelWvwFXyOJ8mh

**Comment by r-marques** [comment]
Looks great, thanks
